server.port = 8087

# Database
# Local Docker Oracle
spring.datasource.url=${config.url:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
spring.datasource.username=${config.username:CONFIG_SERVICE}
spring.datasource.password=${db.config.password}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true