metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      serviceAccount: springboot-serviceaccount
      containers:
        - name: spring-boot
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ${spring.profiles.active}
